const Ziggy = {
    url: "http:\/\/localhost",
    port: null,
    defaults: {},
    routes: {
        login: { uri: "login", methods: ["GET", "HEAD"] },
        logout: { uri: "logout", methods: ["POST"] },
        register: { uri: "register", methods: ["GET", "HEAD"] },
        "password.request": {
            uri: "password\/reset",
            methods: ["GET", "HEAD"],
        },
        "password.email": { uri: "password\/email", methods: ["POST"] },
        "password.reset": {
            uri: "password\/reset\/{token}",
            methods: ["GET", "HEAD"],
            parameters: ["token"],
        },
        "password.update": { uri: "password\/reset", methods: ["POST"] },
        "password.confirm": {
            uri: "password\/confirm",
            methods: ["GET", "HEAD"],
        },
        "v2.clientes.index": { uri: "v2\/clientes", methods: ["GET", "HEAD"] },
        "v2.clientes.listado": {
            uri: "v2\/api\/clientes",
            methods: ["GET", "HEAD"],
        },
        "v2.clientes.store": { uri: "v2\/api\/clientes", methods: ["POST"] },
        "v2.clientes.show": {
            uri: "v2\/api\/clientes\/{id}",
            methods: ["GET", "HEAD"],
            parameters: ["id"],
        },
        "v2.clientes.update": {
            uri: "v2\/api\/clientes\/{id}",
            methods: ["PUT"],
            parameters: ["id"],
        },
        "v2.clientes.destroy": {
            uri: "v2\/api\/clientes\/{id}",
            methods: ["DELETE"],
            parameters: ["id"],
        },
        "v2.clientes.vue": {
            uri: "v2\/clientes-vue",
            methods: ["GET", "HEAD"],
        },
        "clientes.v3.index": { uri: "v3\/clientes", methods: ["GET", "HEAD"] },
        "clientes.v3.store": { uri: "v3\/clientes", methods: ["POST"] },
        "clientes.v3.update": {
            uri: "v3\/clientes\/{cliente}",
            methods: ["PUT"],
            parameters: ["cliente"],
            bindings: { cliente: "id" },
        },
        "clientes.v3.destroy": {
            uri: "v3\/clientes\/{cliente}",
            methods: ["DELETE"],
            parameters: ["cliente"],
            bindings: { cliente: "id" },
        },
        home: { uri: "dashboard", methods: ["GET", "HEAD"] },
        "tareas.create": { uri: "tareas\/crear", methods: ["GET", "HEAD"] },
        "tareas.store": { uri: "tareas", methods: ["POST"] },
        "tareas.edit": {
            uri: "tareas\/{tarea}\/editar",
            methods: ["GET", "HEAD"],
            parameters: ["tarea"],
            bindings: { tarea: "id" },
        },
        "tareas.update": {
            uri: "tareas\/{tarea}",
            methods: ["PUT"],
            parameters: ["tarea"],
            bindings: { tarea: "id" },
        },
        "tareas.confirmDelete": {
            uri: "tareas\/{tarea}\/eliminar",
            methods: ["GET", "HEAD"],
            parameters: ["tarea"],
            bindings: { tarea: "id" },
        },
        "tareas.destroy": {
            uri: "tareas\/{tarea}",
            methods: ["DELETE"],
            parameters: ["tarea"],
            bindings: { tarea: "id" },
        },
        "tareas.completeForm": {
            uri: "tareas\/{tarea}\/completar",
            methods: ["GET", "HEAD"],
            parameters: ["tarea"],
            bindings: { tarea: "id" },
        },
        "tareas.complete": {
            uri: "tareas\/{tarea}\/completar",
            methods: ["POST"],
            parameters: ["tarea"],
            bindings: { tarea: "id" },
        },
        "empleados.index": { uri: "empleados", methods: ["GET", "HEAD"] },
        "empleados.create": {
            uri: "empleados\/crear",
            methods: ["GET", "HEAD"],
        },
        "empleados.store": { uri: "empleados", methods: ["POST"] },
        "empleados.edit": {
            uri: "empleados\/{empleado}\/editar",
            methods: ["GET", "HEAD"],
            parameters: ["empleado"],
            bindings: { empleado: "id" },
        },
        "empleados.update": {
            uri: "empleados\/{empleado}",
            methods: ["PUT"],
            parameters: ["empleado"],
            bindings: { empleado: "id" },
        },
        "empleados.confirmDelete": {
            uri: "empleados\/{empleado}\/eliminar",
            methods: ["GET", "HEAD"],
            parameters: ["empleado"],
            bindings: { empleado: "id" },
        },
        "empleados.destroy": {
            uri: "empleados\/{empleado}",
            methods: ["DELETE"],
            parameters: ["empleado"],
            bindings: { empleado: "id" },
        },
        "empleados.confirmBaja": {
            uri: "empleados\/{empleado}\/baja",
            methods: ["GET", "HEAD"],
            parameters: ["empleado"],
            bindings: { empleado: "id" },
        },
        "empleados.baja": {
            uri: "empleados\/{empleado}\/baja",
            methods: ["POST"],
            parameters: ["empleado"],
            bindings: { empleado: "id" },
        },
        "empleados.confirmAlta": {
            uri: "empleados\/{empleado}\/alta",
            methods: ["GET", "HEAD"],
            parameters: ["empleado"],
            bindings: { empleado: "id" },
        },
        "empleados.alta": {
            uri: "empleados\/{empleado}\/alta",
            methods: ["POST"],
            parameters: ["empleado"],
            bindings: { empleado: "id" },
        },
        "clientes.index": { uri: "clientes", methods: ["GET", "HEAD"] },
        "clientes.create": { uri: "clientes\/crear", methods: ["GET", "HEAD"] },
        "clientes.store": { uri: "clientes", methods: ["POST"] },
        "clientes.confirmBaja": {
            uri: "clientes\/{cliente}\/baja",
            methods: ["GET", "HEAD"],
            parameters: ["cliente"],
            bindings: { cliente: "id" },
        },
        "clientes.baja": {
            uri: "clientes\/{cliente}\/baja",
            methods: ["POST"],
            parameters: ["cliente"],
            bindings: { cliente: "id" },
        },
        "clientes.confirmAlta": {
            uri: "clientes\/{cliente}\/alta",
            methods: ["GET", "HEAD"],
            parameters: ["cliente"],
            bindings: { cliente: "id" },
        },
        "clientes.alta": {
            uri: "clientes\/{cliente}\/alta",
            methods: ["POST"],
            parameters: ["cliente"],
            bindings: { cliente: "id" },
        },
        "clientes.show": {
            uri: "clientes\/{cliente}",
            methods: ["GET", "HEAD"],
            parameters: ["cliente"],
            bindings: { cliente: "id" },
        },
        "cuotas.index": { uri: "cuotas", methods: ["GET", "HEAD"] },
        "cuotas.generarRemesa": {
            uri: "cuotas\/remesa",
            methods: ["GET", "HEAD"],
        },
        "cuotas.create": { uri: "cuotas\/crear", methods: ["GET", "HEAD"] },
        "cuotas.store": { uri: "cuotas", methods: ["POST"] },
        "cuotas.edit": {
            uri: "cuotas\/{cuota}\/editar",
            methods: ["GET", "HEAD"],
            parameters: ["cuota"],
            bindings: { cuota: "id" },
        },
        "cuotas.update": {
            uri: "cuotas\/{cuota}",
            methods: ["PUT"],
            parameters: ["cuota"],
            bindings: { cuota: "id" },
        },
        "cuotas.confirmDelete": {
            uri: "cuotas\/{cuota}\/eliminar",
            methods: ["GET", "HEAD"],
            parameters: ["cuota"],
            bindings: { cuota: "id" },
        },
        "cuotas.destroy": {
            uri: "cuotas\/{cuota}",
            methods: ["DELETE"],
            parameters: ["cuota"],
            bindings: { cuota: "id" },
        },
        "cuotas.papelera": {
            uri: "cuotas\/papelera",
            methods: ["GET", "HEAD"],
        },
        "cuotas.restore": {
            uri: "cuotas\/{id}\/restore",
            methods: ["POST"],
            parameters: ["id"],
        },
        "facturas.confirmar": {
            uri: "facturas\/gestionar\/{cuota}",
            methods: ["GET", "HEAD"],
            parameters: ["cuota"],
        },
        "facturas.generar": {
            uri: "facturas\/generar\/{cuota}",
            methods: ["POST"],
            parameters: ["cuota"],
        },
        "facturas.descargar": {
            uri: "facturas\/descargar\/{factura}",
            methods: ["GET", "HEAD"],
            parameters: ["factura"],
            bindings: { factura: "id" },
        },
        "facturas.enviar": {
            uri: "facturas\/enviar\/{factura}",
            methods: ["POST"],
            parameters: ["factura"],
            bindings: { factura: "id" },
        },
        perfil: { uri: "perfil", methods: ["GET", "HEAD"] },
        "perfil.update": { uri: "perfil", methods: ["PUT"] },
        "tareas.index": { uri: "tareas", methods: ["GET", "HEAD"] },
        "tareas.show": {
            uri: "tareas\/{tarea}",
            methods: ["GET", "HEAD"],
            parameters: ["tarea"],
            bindings: { tarea: "id" },
        },
        "tareas.downloadFile": {
            uri: "tareas\/{tarea}\/descargar",
            methods: ["GET", "HEAD"],
            parameters: ["tarea"],
            bindings: { tarea: "id" },
        },
        "incidencia.create": { uri: "incidencia", methods: ["GET", "HEAD"] },
        "incidencia.store": { uri: "incidencia", methods: ["POST"] },
        "storage.local": {
            uri: "storage\/{path}",
            methods: ["GET", "HEAD"],
            wheres: { path: ".*" },
            parameters: ["path"],
        },
        "storage.local.upload": {
            uri: "storage\/{path}",
            methods: ["PUT"],
            wheres: { path: ".*" },
            parameters: ["path"],
        },
    },
};
if (typeof window !== "undefined" && typeof window.Ziggy !== "undefined") {
    Object.assign(Ziggy.routes, window.Ziggy.routes);
}
export { Ziggy };
